apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-pv4j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-pv4j
    app.kubernetes.io/part-of: ci10t-776-0040-app
  name: devfile-sample-pv4j
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-pv4j
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-pv4j
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0040-tenant/ci10t-776-0040-app/devfile-sample-pv4j@sha256:90c0812de0537362582ee2ede987bcd357cd0ea194fed8e39b6c5837981230db
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
